### ISSUE TITLE
Code colour is very hard to read

### ISSUE THREAD

**Issue by JaneJeon** [TheTastefulToastie/typora-theme-github-dark#1]
When using this theme, the code sections are _very_ hard to read due to the dark colour against dark background, 
<img width="845" alt="screen shot 2019-01-31 at 9 48 12 am" src="https://user-images.githubusercontent.com/24810585/52061995-a9972b00-253d-11e9-887d-36147348b613.png">
in comparison to the default night theme that uses light text on dark background:
<img width="879" alt="screen shot 2019-01-31 at 9 48 26 am" src="https://user-images.githubusercontent.com/24810585/52061996-a9972b00-253d-11e9-9fd9-37710f56786f.png">

The most obvious solution I see is to keep night theme's colours just for the code sections, and keep this theme unchanged otherwise, but really, anything that helps the readability would be nice.

**Comment by JaneJeon** [comment]
I would also like to add that the same problem persists when typing math:
<img width="429" alt="screen shot 2019-01-31 at 9 58 51 am" src="https://user-images.githubusercontent.com/24810585/52062618-d6980d80-253e-11e9-977c-b415e04c6cb7.png">

As you can see, it's nearly impossible to read the dark purple text against a dark background like this.

**Comment by zwkcoding** [comment]
same problem!

**Comment by Vac1911** [comment]
I am super late, however I had a go at replicating github's syntax highlighting. I've only tested it with JavaScript snippets.

Here is a screenshot from my Typora (it maybe hard to see the image edge because i changed the background color to match what github is currently using):

![image](https://user-images.githubusercontent.com/45333542/118037229-8f16a380-b33b-11eb-9c21-ea1a795eb3fd.png)

And here it is on Github:

![image](https://user-images.githubusercontent.com/45333542/118035694-8cb34a00-b339-11eb-9952-f303abb97747.png)

Below is the source code. I can't promise that all the colors will be in the right spots for other languages, but atleast they will be the same colors and readable.

```css
:root {
    --color-code-comment: #8b949e;
    --color-code-constant: #79c0ff;
    --color-code-entity: #d2a8ff;
    --color-code-storage-modifier-import: #c9d1d9;
    --color-code-entity-tag: #7ee787;
    --color-code-keyword: #fb6359;
    --color-code-string: #a5d6ff;
    --color-code-variable: #ffa657;
    --color-code-regexp: #7ee787;
    --code-comment: #8b949e;
    --bg-code: #161b22;
    
    /* Optional to improve selected text readablity */
    --select-text-bg-color: #4995dd;
    --select-text-font-color: #fff;
}

.cm-s-inner .cm-keyword {
    color: var(--color-code-keyword);
}

.cm-s-inner .cm-comment {
    color: var(--color-code-comment);
}

.cm-s-inner .cm-variable,
.cm-s-inner .cm-def {
    color: var(--color-code-variable);
}

.cm-s-inner .cm-string {
    color: var(--color-code-string);
}

.cm-s-inner .cm-entity,
.cm-s-inner .cm-property {
    color: var(--color-code-entity);
}

.cm-s-inner .cm-operator,
.cm-s-inner .cm-number {
    color: var(--color-code-constant);
}

.cm-s-inner .cm-variable-2,
.cm-s-inner .cm-string-2 {
    color: var(--text-color);
}

pre.md-fences {
   border: 1px solid var(--bg-code);
   background-color: var(--bg-code);
}
```
